apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketer-config
  namespace: ticketer
  labels:
    app: ticketer
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
