apiVersion: v1
kind: Service
metadata:
  name: ticketer
  namespace: ticketer
  labels:
    app: ticketer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ticketer
  sessionAffinity: None
